version: '3'
services:
  axigen:
    image: axigen/axigen
    environment:
      - AXIGEN_PRECONFIGURED=yes
      - AXIGEN_ADMIN_PASSWORD=unknownadmin
    ports:
      - 9000:9000
      - 7000:7000
      - 21:21
      - 80:80
      - 25:25
      - 110:110
      - 143:143
    volumes:
      - axigen_data:/axigen/var
volumes:
  axigen_data:
