version: '3.5'
services:
#
# axigen


  axigen:
    image: axigen/axigen
    ports:
      - 80
      - 443
      - 25
      - 9443
      - 110
      - 143
      - 993
      - 995
      - 465
      - 9000
      - 7000
      
      volumes:
      - redis:/axigen/var
       
